# Glosay

**Trail**: A sequence of incident edges in which no link is repeated [(Borgatti, 2005)](https://www.zotero.org/google-docs/?cX2T7s).

**Paths**:  A sequence of incident edges in which neither link nor nodes can be repeated [(Borgatti, 2005)](https://www.zotero.org/google-docs/?EpyVNh). 


**A walk**: Unrestricted sequence of incident edges.
All paths are trails and all trails are walks.
Can be modeled as a Markov process [(Borgatti, 2005)](https://www.zotero.org/google-docs/?4It7K1). 


**Types of node-to-node flow transmission:** It considers the mechanics of dyadic diffusion, namely replication, and transfer.
With regard to replication, this can be serial or parallel.
Overall, this single categorical dimension has three types: transfer, serial duplication, and parallel duplication [(Borgatti, 2005)](https://www.zotero.org/google-docs/?JU0Y9W). 


**Kinds of trajectories flow can take:** On one side, they consider whether or not flow moves in a deterministic manner, that is if flow takes the shortest path to a pre-determined target, or if it moves blindly in an undirected manner.
Also, they consider which kind of graph-theoretic trajectories is used; geodesics, paths, trails, or walks. 
 

**Topology of a network:** The pattern of interconnections among nodes. 


**Node degree:** It is the number of edges linked to a node. 


**Centrality:** The influence of a node on a given network property due to its topological context.
It is the expected value or nodal score in an implicit model of nodal participation in network flows [(Borgatti, 2005)](https://www.zotero.org/google-docs/?LcbEwG)

**Centrality as integration and influence:** In general terms, a node's centrality quantifies its influence or importance in the network.
More precisely, centrality measures how well a node integrates into the network given its structural position.
High centrality means that a node may exert control over other nodes. 

**Centrality analysis:** Identification of (single) nodes that may control a given network function through topological effects.
Different metrics emphasize distinct aspects of topological importance. 

**Adjacency matrix:** A matrix representation of a network in which each entry encodes de presence of a weighted or binary connection (edge) between a unique pair of nodes [(Fornito et al., 2016)](https://www.zotero.org/google-docs/?BpQ9hV)

**Undirected unweighted network:** It is a network where the connections between nodes do not have direction nor weight.
A binary adjacency matrix serves as its representation. 

**Cohesion matrix:**  The entries of the adjacency matrix can contain other metrics different from length-one walks.
These metrics extent to any measure that a pair of nodes can present, including greater walks, shortest paths, etc.
This extended (generalized) definition of the adjacency matrix is known as the cohesion matrix. 

**Types and properties of walks:** A binary adjacency matrix encodes the occurrence of links between pairs of nodes.
More precisely, each of such entries denotes the presence (or absence) of a walk of length one that two nodes (reactions) may share. 

**A walk:**  A continuous trajectory in a network that is allowed to visit the same nodes and links multiple times. 

**Walk type:**  The type of restrictions placed on the walk of interest, which gives rise to other types of metrics such as paths, trails, shortest-paths, etc. 

**Walk property:** distinction between volume or length of the walk type.



**Volume:** When one counts the number of walks of some type.



**Length:** When one measures the length of the walks. 



**Different kinds of cohesion matrices:** Different kinds of cohesion matrices can be build by selecting different types and properties of walks.
All serve to encode the cohesion between pairs of nodes (dyadic cohesion) in the network.



**Node centrality:**   A summarization of the amount of dyadic cohesion in which a given node participates in.
In particular, this summarization is a mathematical reduction (mean or median, for instance) applied to a row of the cohesion matrix. 



**Different kinds of centralities:** Since the cohesion matrix can be defined using different combinations of types and properties of walks, several sorts of centrality emerge.
There are three kinds of centralities: degree-like, closeness-like, and betweenness-like. 



**Radial involvement**: centralities in which the node of interest is at the center of the metric, which means that it is taken as the starting/ending point of any walk [(Borgatti and Everett, 2006)](https://www.zotero.org/google-docs/?9pHP9c). 

## Eigenvector-based centralities

The number of walks in which a node participates as the starting or ending point in a given type of walk.
Derived from cohesion matrices based on walk property of volume.
These centralities count walks, which assume that trajectories can be circuitous and can revisit nodes and edges multiple times.
Also, these measures assume that the flow can take several paths simultaneously [(Borgatti, 2005)](https://www.zotero.org/google-docs/?L3rDnu). 



Based on the properties of the (largest) eigenvector of the adjacency matrix, one can safely assume that a node associated with high eigenvector-based scored is adjacent to nodes that also have high scores.
This allows the interpretation of eigenvector-based centrality as indicative of the influence over other nodes or susceptibility of being influenced by others [(Borgatti, 2005)](https://www.zotero.org/google-docs/?TE1w9d).
This kind of centrality assumes that flow can move throughout (unrestricted) walks,  thus each node can receive or transfer flow via all its neighbors.
Eigenvector-based centrality is indicative of the long-term direct and indirect influence [(Borgatti, 2005)](https://www.zotero.org/google-docs/?F4sQo1). 
 




**Eigenvector centrality (EC).** accounts for the quantity and quality of a node's connections by accounting for its degree and the degree of its neighbors [(Bonacich, 1987; Fornito et al., 2016)](https://www.zotero.org/google-docs/?ndDusv).
For our reaction-projected undirected network with n nodes, the eigenvector centrality of node i (ECi) is proportional to the sum of the centralities of its neighbors.
The eigenvectors (x) and eigenvalues () of the adjacency matrix (A) are employed for the calculation, where the eigendecomposition Ax=x rearranges into:

$$
\tag{1}
EC_i=x_i=11j=1nA_{ij}x_j
$$

here, 1 is the leading eigenvector, i.e., the eigenvector corresponding to the largest (positive) eigenvalue [(Fornito et al., 2016; Newman, 2018)](https://www.zotero.org/google-docs/?AdVbtz).



**Katz centrality (KC).** It gives each node a baseline (constant) greater than zero centrality [(Katz, 1953)](https://www.zotero.org/google-docs/?k2tEhX).
Such a basal amount of centrality is regardless of the node's topological context, so that:

KCi=xi=j=1nAijxj+                                                         (2)

where α and β are positive scalars.
These values control the balance between the pure eigenvector centrality and the basal amount of centrality.
As recommended, we chooseto be one and fixed to be less than the inverse of the largest eigenvalue 1[(Newman, 2018)](https://www.zotero.org/google-docs/?O08AIa). 

The KC provides a solution to the problems encountered with ordinary eigenvector centrality in directed networks.
However, there is no reason in principle why one cannot use KC in undirected networks as well, and there are times when this might be worthwhile.
The idea of adding a constant term to the centrality so that each node gets some weight just by virtue of existing is a natural one.
It allows a node that has many neighbors to have high centrality regardless of whether those neighbors themselves have high centrality, and this could be useful in some applications [(Newman, 2018)](https://www.zotero.org/google-docs/?w77J3I).



**PageRank (PR).** [(Page et al., 1999)](https://www.zotero.org/google-docs/?pk4Emg)

$$
PRi=xi=j=1nAijxjkjout+
$$

## Closeness-based centralities

Mainly, they account for the extent to which a node connects to others nodes via the shortest paths.
A node with a short average path length can interact with many network elements via only a few links, suggesting that it is topologically central [(Fornito et al., 2016)](https://www.zotero.org/google-docs/?p4MPDY).
Derived from cohesion matrices based on walk property of length. 

Closeness is based on the mean of all the distances from one node to the rest of the others, where the distance is usually the shortest path [(Freeman, 1978)](https://www.zotero.org/google-docs/?jOEn8B).
Closeness may be interpreted as an index of the expected time of arrival of something moving throughout the network, assuming that it moves through the shortest paths or at least it tends to prioritize them [(Borgatti, 2005)](https://www.zotero.org/google-docs/?daZilW).
A node that scores high in closeness is expected to be well-located to rapidly receive what is flowing through the network, as long as it manly flows via shortest paths and undergoes parallel duplication.
In interpreting closeness as the time of arrival, it is implicitly assumed that the flow "knows" how to arrive at its destination  [(Borgatti, 2005)](https://www.zotero.org/google-docs/?RQPYCi). 

**Closeness centrality (CC).** It measures the mean distance from a node to other nodes.
Let dijbe the shortest distance from node ito j, then the mean distance fromito every node is:

$$
\tag{3}
li=1n-1j=1ndij
$$

then, the CC for node iis [(Beauchamp, 1965)](https://www.zotero.org/google-docs/?HhGV2q):


$$
CCi=1li=n-1j=1ndij                                                         (4)
$$
**Information centrality (IC).** [(Stephenson and Zelen, 1989)](https://www.zotero.org/google-docs/?uqLXx2)

$$

Ii=nj(Iij)-1

$$

## Betweenness-based centralities



It indicates the node's capacity for serving as a mediator (intermediate connection) between pairs of nodes.
Betweenness-like metrics count the number of the pairwise walks (instances of connections between node pairs) in which the node of interest is involved as an interior node.
In this sense,  betweenness-like centralities are considered measures of medial involvement.
These measures assume that what flows from node to node is indivisible then should use one single path [(Borgatti, 2005)](https://www.zotero.org/google-docs/?q9lTxH).



Betweenness is regarded as a measure of the amount (volume) of traffic moving from each node to every other that passes through a node of interest.
Thus betweenness measures the extent to which a node of interest controls the flow between node pairs.
These type of measures of centrality assumes the characteristics of a package delivery process, namely an indivisible quantity transferred mostly via geodesics from node to node that eventually arrives at its predefined destination [(Borgatti, 2005)](https://www.zotero.org/google-docs/?CslIO1).

**Betweenness centrality (BC).** It measures the proportion of shortest paths between all node pairs in the network that pass through a given index node [(Freeman, 1977)](https://www.zotero.org/google-docs/?jVQzML), so that:

$$

BCi=1n2stnstigst

$$

**Communicability betweenness centrality (CBC).** This measure of betweenness considers the shortest paths between pair of nodes but also accounts for other longer paths.
Specifically,  CBC counts the number of walks between nodes p and q in which the node r participates, weighting by the length of the path [(Estrada et al., 2009)](https://www.zotero.org/google-docs/?YvU1Ip), formally:

$$

Gpq=k=0(Ak)pqk!

$$

$$

CBCi=1CpqGprqGpq,   C=(n-1)2-(n-1)

$$

**Flow betweenness centrality (CBC)**.
[(Freeman et al., 1991)](https://www.zotero.org/google-docs/?cwMYnI)


## Basics of the nodal contribution to subnetwork centrality

**The centrality of the energy metabolism:**  It is a summarization (via geometric mean) of the single centralities of the reactions that belong to the cellular energy metabolism.



**Cohesiveness:** the concept of centrality but applied to groups of nodes.
This is because centrality is a property exclusively to the single nodes.



**Network cohesiveness:** It summarizes all node centralities---the reduction of the cohesion matrix to a single quantity.



**Subnetwork cohesiveness:**  It is a summarization of a subset of node centralities. 
How well integrated a group is. 



**Delta centrality:** It is a centrality measure that assumes that the network response to removing a node determines the node's importance.
More precisely, delta centrality measures the variation of the network cohesiveness upon single node removal. 



-   **Interpretation (single node -> whole network) 1:**  It is the global contribution of a node to maintaining the network cohesiveness. 



**Nodal contribution to the centrality of the energy metabolism (single node -> subnetwork):** measures the variation of a subnetwork (energy metabolism) cohesiveness upon single node removal. 
Find nodes that may control the integration (or level of participation) of a given subnetwork into the network.
The latter allows us to find structural modulators of the energy metabolism. 



-   **Interpretation (single node -> subnetwork) 2:** It is the single nodal contribution to subnetwork cohesiveness. 



**Hub:** It is a topologically central node.
Different measures of centrality can distinguish between different types of hubs.



**Consensus classification of hubs:**  It is a robust classification of individual nodes.
It is used when potential hubs have several topological characteristics.
Findings that are not biased by any single definition of centrality. 



## Correlations between nodal contributions



**Positive nodal contribution:** When the structural position of a node favors the centrality of the energy metabolism.



**Negative nodal contribution:** When the structural position of a node reduces the centrality of the energy metabolism.



**Positive pair-wise correlation between nodal contributions:** When both nodes positively, or negatively, contribute to the centrality of the energy metabolism.



**Negative pair-wise correlation between nodal contributions:** When one node positively contributes and the other contributes negatively, and vice versa.



## Correlations as indicative of two-core periphery structure



The negative correlation between two nodal contributions (to a subsystem centrality) means that one node belongs to a core-periphery structure while the other is outside of such a structure. 
 



The presence of nodes outside the core-periphery implies that the whole network is sparse.
Removing such foreign nodes becomes the network more integrated.
Then foreign nodal contributions are expected to be negative.
Our metabolic subsystems are located inside a core-periphery structure, that is the cell where they belong, but outside the core-periphery of the other cell.
Hence, nodal contributions coming from inside the core-periphery would positively affect the centrality of their own subsystem.
On the other hand, nodal contributions coming from outside would negatively impact the centrality of such a subsystem.
More precisely, the presence of foreign nodes implies that the subsystem is poorly integrated into the whole network.
Thus by removing such nodes the subsystem will be better integrated into the rest of the network.
In this sense, a negative correlation between two nodal contributions indicates that one node is inside the core-periphery where the subsystem belongs while the other is outside. 



Since each cellular metabolism is characterized by a core-periphery structure, and pairwise correlations between nodal contributions allow to distinguish whether or not the pair of nodes belong to the same core-periphery, such correlations predict to which cell each node belongs.
These results show that our method effectively assesses the integration of a cellular subsystem to the rest of the network.
Therefore, such a method can be useful to find topological modulators of the subsystems for our case, which may control the energy metabolism at the network-wise level.
Such modulators can be associated with enzymes or transporters that can be sensible targets for therapy or investigation. 





## Flux-based analysis



**Genome-scale reconstructed metabolic networks:** These are curated and systematized knowledge base that collects all the available biochemical, genetic, and genomic information that is available for a given cellular metabolism [(Palsson, 2015; Price et al., 2004; Thiele and Palsson, 2010)](https://www.zotero.org/google-docs/?sfgbZb).



Genome-scale models (GEMs): The translation of a reconstructed network into a mathematical formalism that allows computation and prediction of phenotypes.



**Reduced costs:**  It is the amount by which the objective function changes upon an increase in an internal flux.
A reduced cost (ri) can be interpreted as the sensitivity of the objective function with respect to the change in the ith flux value.
In biological terms, this can be interpreted in the following manner: If a flux Ji has a reduced cost of ri in a particular FBA solution and this flux value is increased by ΔJi, then the objective function value will be changed to Z + riΔJi [(Maarleveld et al., 2013)](https://www.zotero.org/google-docs/?kkBM48)



**Constraints:** Cellular functions are constrained by myriad different factors.
Mathematically, constraints are described with balance equations and inequalities.
The imposition of different constraints leads to a space of achievable metabolic states. 



**Constraint-based analysis methods:** The fundamental equations describing the cellular events may be hard to formulate and define.
Nonetheless, the boundary conditions or the constraints in which cells operate are easier to identify, state, and use [(Palsson, 2015)](https://www.zotero.org/google-docs/?wLjwjO). 
these constraints are those in which functional states take place. 



**Functional states in metabolic networks: The cellular metabolism is** subjected to several constraints, including those emerging from physicochemical laws and the environment.
A variety of functional states are achievable under such constraints.
The functional states correspond to the physiologically observable phenotypes.
More precisely, any cellular metabolism has a characteristic state that one recognizes as a physiological (homeostatic) state.
In this sense, the fluxes that account for such a functional state becomes the dominant variables.



**Steady-state:** The metabolic state where no accumulation nor depletion of metabolites is observed due to the balance between fluxes.
**T**he state in which the internal metabolites are produced and consumed in a flux-balance fashion [(Fang et al., 2020)](https://www.zotero.org/google-docs/?VWFa4d).



**The steady-state assumption:** Despite networks are not strictly in steady-state, many homeostatic states are close to being steady, and over time-averaged, flux balances satisfy the steady-state.
Such a feature makes flux balance analysis quite useful for study functional metabolic phenotypes [(Palsson, 2015)](https://www.zotero.org/google-docs/?MhytCd). 



**Time-scale hierarchy and fast subsystems, quasi-steady states:** Usually, it is assumed that fast subsystems are in a quasi-steady state.
This means that the subsystem is in a steady-state internally but has inputs and outputs to which the balance is not zero.
For instance, uptake rates and metabolite excretions can be net flux while the internal metabolism is in steady-state  [(Palsson, 2015)](https://www.zotero.org/google-docs/?fzvgk9).
Hence, one can state that cellular metabolism adjusts its fluxes rapidly upon changing enviroments. 




Cytosolic ATP and ADP levels are unperturbed across a wide range of physiological workloads, indicating strong flux coupling among sodium efflux and oxidative phosphorylation[(Baeza-Lehnert et al., 2019)](https://www.zotero.org/google-docs/?9FzG6r)**.** The connectivities created between the reactions are 'soft' since the reactions in which a metabolite participates can have varying flux levels with no fixed ratios [(Palsson, 2015)](https://www.zotero.org/google-docs/?Lj076o).



Subsystem in a metabolic network: A segmentation in the network into subnetworks by drawing "virtual" boundaries. 




**The role of regulation:**  Cells have to have mechanisms able to select for physiologically relevant states.
A  way to select useful states is the deployment of regulatory networks.
Regulatory mechanisms entail the expression of the "suitable" metabolic phenotype.
This is attained by regulating the expression of genes or by regulating the activity of enzymes. 




## Modeling through optimization





**Genome-scale metabolic reconstruction:** A curated, systematized, and validated knowledge base of all reactions and metabolites occurring in a given cellular metabolism.



**Constraints-based metabolic model:** The computation of metabolic flux can be done from a mathematical model of the metabolic network. 
This model is based on stoichiometric, thermodynamic, and physicochemical constraints.



**Stoichiometric matrix:** The most fundamental element of a constraint-based metabolic model is the stoichiometric matrix.
The matrix's entries correspond to the stoichiometric coefficients of substrates and products (metabolites).
Each row in the matrix represents a metabolite, while each column denotes a reaction (exchanges and interchanges are also considered in this category); thus, a coefficient is present if a metabolite participates in a given reaction. 



Each column of the S matrix represents a reaction (or transport) and is constrained by the principles of physics and chemistry, such as mass balance.
On the other hand, every row describes all reactions in which the corresponding metabolite participates, hence rows indicate how reactions are connected   [(Palsson, 2015)](https://www.zotero.org/google-docs/?sgNCBq).



The S matrix, by definition, is a connectivity matrix that encodes the topology of a network.
This structural information results in the definition of pools and pathways that are associated with the null spaces of S.
All the elements of the matrix are in the same order of magnitude and are integers, making it a numerically well-conditioned matrix   [(Palsson, 2015)](https://www.zotero.org/google-docs/?VEMyAJ).





## The stoichiometric matrix as a linear transformation





In order to compute fluxes, the stoichiometric matrix (S) is associated with a vector of fluxes (v); thus, the mass metabolite balance can be represented as de multiplication between both (S*v).
If one assumes no depletion nor accumulation of metabolites (steady-state) and that S is square, the system of equations (S*v=0) may be solved, and the fluxes compute.
However, constraints-based metabolic models yield more reactions than metabolites, meaning data S is rectangular.
Then, one ends up with a solution space of flux vectors (feasible steady-state solutions). 





**FBA:** In order to determine a unique flux vector, henceforth metabolic state,  optimality conditions can be imposed.
It can be assumed that the most probable metabolic state is that where fluxes are optimized to satisfy a given metabolic objective.
In this sense, an objective function is defined, while the steady-state equations serve as constraints.
Once solved, the solution of the objective is associated with an optimal metabolic state. 



**Incidence matrix:** The matrix S also can be interpreted as an incidence matrix of a bipartite graph.
Here, the stoichiometric coefficients are interpreted as weighted links between two groups of nodes (partitions), namely the metabolites and the reactions. 



**Unipartite projection:** Since we are interested in finding critical enzymes, the incidence matrix was converted to its unipartite projection of the reaction.
In this new matrix, the entries denote the number of metabolites that two reactions have in common, and the diagonal is set to zero.
The unipartite projection can be viewed as the weighted adjacency matrix of the reactions. 
Since we are interested in the fundamental structure of the network, avoiding any information about the function, we binarized the weighted adjacency matrix of the reactions. 



## Modeling functional states in metabolic networks

The metabolic phenotype of a cell is the set of all functional states that the metabolic network can present.
The metabolic phenotype results from the genetic programs of the cell type and the environmental variables.
The realization of a specific functional state depends on the regulatory events that take place in given circumstances.
Functional states are modeled via an objective function that allows computing the distribution of fluxes that best comply with the objective function.
Objective functions are useful to model biological states where is a certainty that the metabolic network optimizes a defined subset of fluxes and operates under a pseudo-steady state.


